command: [
  "streamlit",
  "run",
  "app.py"
]
env:
  - name: sarvam_api_key
    valueFrom: sarvam_api_key

  - name: NYAYA_LOCAL_ONLY
    value: "true"

  - name: NYAYA_DISABLE_PAGEINDEX
    value: "true"
